### ISSUE TITLE
[[international-specs#char_string|Defining 'string']] doesn't link

### ISSUE THREAD

**Issue by jyasskin** [speced/bikeshed#2978] opened 2024-12-04 13:31 UTC
[[international-specs#char_string|Defining 'string']] produces

> [[international-specs#char_string|Defining &lt;a class="property css" data-link-type="property">‘string’&lt;/a>]]

[[international-specs#char_string|Defining \'string']] produces

> [[international-specs#char_string|Defining 'string']]

[[international-specs#char_string|Defining string]] produces

> [Defining string](https://w3c.github.io/bp-i18n-specdev/#char_string)

They should all produce a link to the [[international-specs]] spec (or its [ED](https://w3c.github.io/bp-i18n-specdev)).

**Comment by tabatkins** [comment] 2024-12-05 00:59
This is actually just (yet another) dupe of #832. I've been sitting on a fix for this for *months* because verifying that all the test changes are reasonable (and slowly tweaking things when they're not) is so tedious, but I'm getting that finished this month, guaranteed.

(The first will still give an error, tho, since you're still using the CSS autolinking syntax and thus producing a nested `a`. It'll just be a different, fairly informative error, since I can detect that I'm in the middle of parsing the outer autolink.)

**Closed by tabatkins** 2024-12-05 00:59 UTC
