### ISSUE TITLE
Add a non-normative container that gets stripped in the output

### ISSUE THREAD

**Issue by domenic** [speced/bikeshed#1193] opened 2018-02-22 23:32 UTC
I try to liberally use `<div class="non-normative">` or `<span class="non-normative">` to help with normative reference and accidental 2119 detection. But, this ends up in my output.

This doesn't impact anything visually, but feels a bit unclean. It'd be nice if there were a way to mark up something as non-normative without impacting the built result.

(Understandably, this is pretty low priority.)

**Comment by tabatkins** [comment] 2018-03-05 21:15
Are you ok with adding more markup, like an attribute saying to remove the element from the output (and promote its children)? Or would you prefer a shorthand specifically for this purpose?

**Comment by domenic** [comment] 2018-03-06 01:51
Extra markup sounds totally fine.

**Comment by jyasskin** [comment] 2021-09-09 23:46
Same as #954, right?

**Comment by jyasskin** [comment] 2023-02-01 01:08
Duplicate of #954.

**Closed by jyasskin** 2023-02-01 01:08 UTC
