### ISSUE TITLE
Install fails with latest (github) bikeshed

### ISSUE THREAD

**Issue by svgeesus** [speced/bikeshed#2465] opened 2023-02-10 19:47 UTC
Attempting to install a fresh checkout of bikeshed:

```
Installing collected packages: urllib3, about-time, multidict, grapheme, alive-progress, bikeshed
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.13
    Uninstalling urllib3-1.26.13:
      Successfully uninstalled urllib3-1.26.13
  Attempting uninstall: multidict
    Found existing installation: multidict 6.0.3
    Uninstalling multidict-6.0.3:
      Successfully uninstalled multidict-6.0.3
  Running setup.py develop for bikeshed
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/chris/Documents/GitHub/bikeshed/setup.py'"'"'; __file__='"'"'/mnt/c/Users/chris/Documents/GitHub/bikeshed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /mnt/c/Users/chris/Documents/GitHub/bikeshed/
    Complete output (42 lines):
    running develop
    /tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    WARNING: The user site-packages directory is disabled.
    Checking .pth file support in /home/chris/.local/lib/python3.8/site-packages
    /usr/bin/python3 -E -c pass
    TEST PASSED: /home/chris/.local/lib/python3.8/site-packages appears to support .pth files
    /tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/chris/Documents/GitHub/bikeshed/setup.py", line 10, in <module>
        setup(
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1213, in run_command
        super().run_command(command)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
        cmd_obj.ensure_finalized()
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/command/develop.py", line 52, in finalize_options
        easy_install.finalize_options(self)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 311, in finalize_options
        self.local_index = Environment(self.shadow_path + sys.path)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1044, in __init__
        self.scan(search_path)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in scan
        self.add(dist)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1096, in add
        dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2631, in hashcmp
        self.parsed_version,
      File "/tmp/pip-build-env-aqxl8wl6/overlay/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2685, in parsed_version
        raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
    pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/chris/Documents/GitHub/bikeshed/setup.py'"'"'; __file__='"'"'/mnt/c/Users/chris/Documents/GitHub/bikeshed/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
```

Ubuntu Linux running on WSL2 on Windows 11:

```
chris@SuperNomad:/mnt/c/Users/chris/Documents/GitHub/bikeshed$ uname -a
Linux SuperNomad 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

This is a regression because I was able to build an older checkout of bikeshed earlier on the same machine.

**Comment by tabatkins** [comment] 2023-02-10 19:58
*What* in the *hell*.

Uhhhhhh, would mind bisecting to find which commit actually triggers the failure? I can try to reproduce later when I get home and have access to a Windows machine.

**Comment by tabatkins** [comment] 2023-02-10 20:08
I suspect you're running into [this issue](https://github.com/pypa/setuptools/issues/3772), which would be out of my control - it's due to your *system* having some built-in python packages that don't have conforming version numbers. Note that nothing in any of my packing files (`Pipfile`, `Pipfile.lock`, `requirements.txt`) have anything like that version - in fact, the string "ubuntu" *solely* appears in one of the GitHub CI files, which are completely irrelevant to the bikeshed runtime.

And looking into it further, the person reporting that issue is in fact getting the *identical* error message as you. So I'm betting that *any* version of Bikeshed will trigger the same, because it was actually a system update of some kind that caused the breakage.

**Comment by tabatkins** [comment] 2023-02-10 20:13
That said, [this commit](https://github.com/canonical/canonicalwebteam.discourse/commit/e736b74e91b2f98566a3e38565cd6ffe854bb756) suggests a temporary fix, until ubuntu publishes fixed versions of the system packages that are offending here.

**Comment by tabatkins** [comment] 2023-02-10 21:41
Gonna close this because I'm pretty certain this is a system problem, not a Bikeshed problem.

**Closed by tabatkins** 2023-02-10 21:41 UTC
Labels: bug
